def get_captions_for_topic(topic):
    topic = topic.strip().lower()
    captions_dict = {
        "coding": [
            "WHEN YOUR CODE WORKS ON THE FIRST TRY.",
            "DEBUGGING: THE NEVER-ENDING STORY.",
            "WHEN YOU FIX ONE BUG AND THREE MORE APPEAR.",
            "EAT. SLEEP. CODE. REPEAT.",
            "I TURN COFFEE INTO CODE.",
        ],
        "cats": [
            "I WORK HARD SO MY CAT CAN HAVE A BETTER LIFE.",
            "CAT HAIR, DON'T CARE.",
            "LIFE IS PURR-FECT WITH CATS.",
            "MY CAT IS MY BOSS.",
            "SORRY, I CAN'T. MY CAT SAID NO.",
        ],
        "exams": [
            "STUDYING: EXPECTATION VS REALITY.",
            "WHEN YOU SEE THE FIRST QUESTION AND PANIC.",
            "THAT MOMENT YOU REALIZE YOU STUDIED THE WRONG CHAPTER.",
            "EXAMS: TESTING MY GUESSING SKILLS SINCE FOREVER.",
            "I WISH GOOGLE WAS ALLOWED IN EXAMS.",
        ],
        "movies": [
            "JUST ONE MORE MOVIE, I PROMISE.",
            "EATING POPCORN LIKE IT'S MY JOB.",
            "MOVIE NIGHT IS EVERY NIGHT.",
            "CAN QUOTE THIS MOVIE BETTER THAN THE ACTORS.",
            "PAUSED MY LIFE FOR THIS FILM.",
        ],
        "sports": [
            "EAT. SLEEP. SPORTS. REPEAT.",
            "WIN OR LOSE, WE STILL ORDER PIZZA.",
            "GAME DAY IS THE BEST DAY.",
            "I'M JUST HERE FOR THE SNACKS.",
            "MY BLOOD TYPE IS SPORTS.",
        ],
        "music": [
            "WHEN THE BEAT DROPS, SO DO MY PROBLEMS.",
            "MUSIC IS MY ESCAPE.",
            "LIFE WITHOUT MUSIC WOULD B FLAT.",
            "TURNING UP THE VOLUME ON LIFE.",
            "MY PLAYLIST UNDERSTANDS ME.",
        ],
        "friends": [
            "FRIENDS DON'T LET FRIENDS DO SILLY THINGS... ALONE.",
            "WE'LL BE FRIENDS UNTIL WE'RE OLD AND SENEILE... THEN WE CAN BE NEW FRIENDS.",
            "GOOD TIMES + CRAZY FRIENDS = AMAZING MEMORIES.",
            "REAL FRIENDS DON'T CARE IF YOUR HOUSE IS CLEAN.",
            "FRIENDS: THE FAMILY WE CHOOSE.",
        ],
        "weekend": [
            "WEEKEND FORECAST: 100% CHANCE OF CHILL.",
            "SATURDAY IS FOR ADVENTURES, SUNDAY IS FOR NAPS.",
            "DEAR WEEKEND, STAY FOREVER.",
            "WEEKENDS ARE TOO SHORT FOR BAD VIBES.",
            "MONDAY IS SO FAR AWAY.",
        ],
        "travel": [
            "CATCH FLIGHTS, NOT FEELINGS.",
            "WANDERLUST: A NEVER-ENDING DESIRE TO TRAVEL.",
            "I NEED SIX MONTHS OF VACATION, TWICE A YEAR.",
            "PASSPORT IN ONE HAND, CONFIDENCE IN THE OTHER.",
            "TRAVEL IS THE ONLY THING YOU BUY THAT MAKES YOU RICHER.",
        ],
        "food": [
            "I'M ON A SEAFOOD DIET. I SEE FOOD AND I EAT IT.",
            "FOOD IS MY LOVE LANGUAGE.",
            "EAT WELL, LAUGH OFTEN.",
            "MY HOBBY? EATING.",
            "LIFE IS SHORT. EAT DESSERT FIRST.",
        ],
        "gaming": [
            "JUST FIVE MORE MINUTES... PROMISE.",
            "EAT. SLEEP. GAME. REPEAT.",
            "I PAUSED MY GAME TO BE HERE.",
            "LEVELING UP IN LIFE AND IN GAME.",
            "GAMERS DON'T DIE, THEY RESPAWN.",
        ],
        "work": [
            "WORKING HARD OR HARDLY WORKING?",
            "I SURVIVED ANOTHER MEETING THAT SHOULD HAVE BEEN AN EMAIL.",
            "COFFEE: BECAUSE ADULTING IS HARD.",
            "FRIDAY IS MY SECOND FAVORITE F WORD.",
            "I'M NOT LAZY, I'M ON ENERGY-SAVING MODE.",
        ],
        "school": [
            "SCHOOL: WHERE MEMES ARE BORN.",
            "CAN I HAVE A RECESS FROM LIFE?",
            "HOMEWORK: THE REAL VILLAIN.",
            "SCHOOL DAYS ARE THE BEST DAYS.",
            "WHEN THE BELL RINGS, I'M GONE.",
        ],
        "pets": [
            "MY PET THINKS I'M AWESOME.",
            "PET HAIR IS MY GLITTER.",
            "WHO RESCUED WHO?",
            "LIFE IS BETTER WITH PAWS.",
            "MY PET IS CUTER THAN YOURS.",
        ],
        "memes": [
            "MEMES ARE MY LOVE LANGUAGE.",
            "WHEN LIFE GIVES YOU LEMONS, MAKE MEMES.",
            "I SPEAK FLUENT MEME.",
            "MEMES: THE CURE FOR EVERYTHING.",
            "CAN'T STOP, WON'T STOP MEMEING.",
        ],
        "parties": [
            "I'M HERE TO PARTY AND EAT CAKE.",
            "DANCE LIKE NO ONE'S WATCHING.",
            "PARTY MODE: ACTIVATED.",
            "SORRY, CAN'T HEAR YOU OVER THE MUSIC.",
            "LET'S GET THIS PARTY STARTED!",
        ],
        "vacation": [
            "VACATION MODE: ON.",
            "TAKE ONLY MEMORIES, LEAVE ONLY FOOTPRINTS.",
            "SUN, SAND, AND A DRINK IN MY HAND.",
            "OUT OF OFFICE, INTO PARADISE.",
            "I NEED A SIX-MONTH VACATION, TWICE A YEAR.",
        ],
        "shopping": [
            "SHOPPING IS MY CARDIO.",
            "I COULD GIVE UP SHOPPING, BUT I'M NOT A QUITTER.",
            "KEEP CALM AND GO SHOPPING.",
            "I HAVE ENOUGH CLOTHES... SAID NO ONE EVER.",
            "RETAIL THERAPY IS REAL.",
        ],
        "technology": [
            "TECH SUPPORT: HAVE YOU TRIED TURNING IT OFF AND ON?",
            "I SPEAK FLUENT WIFI.",
            "UPDATING... PLEASE WAIT.",
            "TECHNOLOGY: MAKING LIFE EASIER, OR IS IT?",
            "404: MOTIVATION NOT FOUND.",
        ],
        "fitness": [
            "SORE TODAY, STRONG TOMORROW.",
            "I WORK OUT... JUST KIDDING, I TAKE NAPS.",
            "RUNNING LATE IS MY CARDIO.",
            "SWEAT NOW, SHINE LATER.",
            "EXERCISE? I THOUGHT YOU SAID EXTRA FRIES.",
        ],
        "telugu": [
            "NENU LOCAL, NENU MASS.",
            "CHILL BRO, LIFE LO TIME UNDHI.",
            "EM CHEYALI ANUKUNTUNNA.",
            "BIRYANI IS MY LOVE LANGUAGE.",
            "HYDERABAD ZINDABAD!",
            "MIND BLOCK AYYINDI.",
            "SINGLE BUT READY FOR BIRYANI.",
            "WORK CHEY, MEME CHUDU.",
            "TELUGU VADINI, PROUD GA UNNA.",
            "COOL GA UNDADAM MANA STYLE.",
            "LIFE LO SORRY, LOVE LO STORY.",
            "NAKU ARDHAM KALEDHU, KANI BAAGUNDI.",
            "EASY GA UNDADAM, BUSY GA KADU.",
            "FRIENDS ANTE FAMILY LAANTI.",
            "BOSS ANTE NENU.",
            "TIME LE, CHILL LE.",
        ],
        "famous":[
            "LET THEM KNOW, UNCLE!",
            "VIGNANA PRADARSHANALU VODDU.",
            "CHUDU OKA VAIPE CHUDU.",
            "ASSALEKKATLEDU MAMA.",
            "KICK KOSAM.",
            "TELUGU QUOTE NAA SAAVU NENU SASTHA NEEKENDHUKU.",
            "TELIDU GURTHULEDU MARCHIPOYA.",
            "I WANT RESPECT.",
            "NA SAAVU NENU SASTA NEEKENDHUKU.",
            "MEERU MARIPOYARU SAAR...",
            "OREI UPDATE AVVANDRA!",
            "UCHITA SALAHALU IVVAKU.",
            "THEY PAID NO?",
            "STRAIGHT OUTTA HYDERABAD.",
        ]
    }

    default_captions = [
        f"WHEN YOU'RE INTO {topic.upper()} LIFE.",
        f"KEEP CALM AND ENJOY {topic.upper()}.",
        f"CAN'T STOP THINKING ABOUT {topic.upper()}.",
        f"THIS IS WHAT {topic.upper()} LOOKS LIKE.",
    ]
    return captions_dict.get(topic, default_captions)